### ISSUE TITLE
Pytriangle does not work in Windows 10

### ISSUE THREAD

**Issue by scoleli** [pletzer/pytriangle#8]
Pytriangle does not work on my Windows 10 system with Python 3.8.5 (Ananconda) and Visual Studio 2019 Build Tools C-compiler (latest 2019 version).
I tested the package with `test_regions.py`: no error messages were shown in my python console, but no print results were given too. After some debugging, I found that Python stops the execution without errors when `triangulate` is called (line 36 in `test_regions.py`; line 160 in `triangle.py`), but the mesh is not generated at all.
I downloaded the repository and then I installed the package via: `pip install pytriangle`.
I tried to solve the issue by uninstalling the package and then installing it again with: `python setup.py install`.
With both setup methods no errors were shown during installation process, but the anomalous behaviour with `test_regions.py` still remains.
I really appreciate any help.

**Comment by pletzer** [comment]
Thanks @scoleli for describing the problem. I'll see if I can get hold of a windows laptop to reproduce the problem.

**Comment by pletzer** [comment]
Hi @scoleli I was able to reproduce the problem on Windows. It seems to be related to poolalloc in the triangle code. More investigations are needed.

**Comment by pletzer** [comment]
Hi @scoleli: Can you check that the latest version works for you on Windows? Thanks.

**Comment by scoleli** [comment]
Hi @pletzer. Yes, now pytriangle is fully portable again.
The latest version works properly on my Windows 10 laptop and also on my office desktop. 
Thanks for your precious help.
